input {
  beats {
    port => 5044
  }
}

filter {
  # optional filters to parse logs
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "docker-logs-%{+YYYY.MM.dd}"
  }
}
